### PR TITLE
Prompt

### LINKED ISSUE #36: Let's build a simpler ux for apps to request access.
Build a way for apps to link to your site, and generate an application password that is then redirected back.

### PR DESCRIPTION
**Pull request by georgestephanis**
Mockup: https://cloudup.com/cXDserZRH_Y

Very much a work in progress, **_not yet ready for merging._**

The idea is to give a page in wp-admin where you can send a user, they can authenticate via wp-login.php if needed, then manually approve (or reject) it and it will send the user back to the app with an application password in tow that the app can store and use.

It saves the user from having to find their profile page and create and retype or copy/paste an application password.  Should be more understandable.

Fixes #36

### CODE REVIEW

**Comment by georgestephanis** [comment]
To Use:

Direct the user seeking to authenticate to the following URL:

http://example.com/wp-admin/admin.php?page=auth_app

The following GET variables are supported currently to append to ^^ that url

`app_name` - ( required-ish ) - The human readable identifier for your app.  This will be the name of the generated application password for future reference, so I recommended to structure it like ... "WordPress Mobile App on iPhone 5" or something.
`success_url` - ( recommended ) - The URL that you'd like the user to be sent to if they approve the connection.  Two GET variables will be appended when they are passed back -- `user_login` and `password` -- these credentials can then be used for API calls.  If the `success_url` variable is omitted, a password will be generated and displayed to the user, to manually enter into your application.
`reject_url` - ( optional ) - If included, the user will get sent there if they reject the connection.  If dropped, they'll just get sent to `admin_url()` instead.  Honestly, I'm consider dropping this as a distinct variable, and just having them get forwarded to `success_url` instead, but without the username or password details. ¯\_(ツ)_/¯

**Comment by georgestephanis** [comment]
For the record, this should be totally mergeable at this point.

**Comment by georgestephanis** [comment]
Vizrec for flow with this change:

app-pass-auth-flow-1
app-pass-auth-flow-2
app-pass-auth-flow-3
app-pass-user-page

**Comment by georgestephanis** [comment]
cc: @adamsilverstein

**Comment by ahmadawais** [comment]
Thank you for all your work on this, @georgestephanis I use it flawlessly on my course platform :)

**Pull request merged**
