### PR TITLE
Add dev-lib

### PR DESCRIPTION
**Pull request by valendesigns**

### CODE REVIEW

**Comment by valendesigns** [comment]
@georgestephanis This is ready for merge. There is going to be a lot of code standards clean up that I can get to later in the week, but for now this will facilitate PHPUnit testing and make generating the readme.md from the readme.txt as easy as creating a symlink to the `pre-commit` hook, which runs the tests, checks CS issues, and regenerates the readme.md before the commit is final. Cheers!
```
cd .git/hooks && ln -s ../../dev-lib/pre-commit . && cd -
```

**Comment by valendesigns** [comment]
I almost forgot, please activate Travis when you get a moment.

**Comment by georgestephanis** [comment]
This looks good to me, @JeffMatson -- any thoughts before merging?

**Comment by JeffMatson** [comment]
Just woke up, so best for me not to look at these things at the moment.  I'll check it out in a few. :)

**Comment by JeffMatson** [comment]
Looks solid to me.  I see some things that can be tweaked in the readme, but that's another commit entirely.

Ready for merge.

**Comment by valendesigns** [comment]
:+1:

**Comment by georgestephanis** [comment]
I think I've got travis-ci set up correctly.

**Comment by valendesigns** [comment]
Did you turn Travis on after merging? The build didn't run for the merge to master and that may be why.

**Comment by valendesigns** [comment]
@georgestephanis Did you activate Travis here https://travis-ci.org/profile

**Comment by georgestephanis** [comment]
@valendesigns Yeah -- I merged, then activated.  My guess is it will kick in in the next pull request?

**Pull request merged**
