### PR TITLE
Add/create password modal

### PR DESCRIPTION
**Pull request by kjbenk**
Here is a first version of an easier to understand password creation process based on the issue https://github.com/georgestephanis/application-passwords/issues/12

### CODE REVIEW

**Comment by JeffMatson** [comment]
Awesome!  I took a quick glance at it and made a few comments.  I'll take a deeper look at it tonight if nobody else has already.

**Comment by kjbenk** [comment]
I looks like I added some modifications from within the other PR https://github.com/georgestephanis/application-passwords/pull/14 to this one.  Once I removed these references the PR will be up to par.

**Comment by JeffMatson** [comment]
Awesome.  I'll do some testing tonight when I get home.

**Comment by JeffMatson** [comment]
Looks like this pull request lost the readme.txt changes somewhere.  Chuck in another pull request for that and I'll merge it.

**Pull request merged**
